import json
import argparse

MAPPING = {
    "cyclone": "cyclone impact",
    "harvest devastation": "low crop yield",
    "rising inflation": "economic situation affecting people",
    "prolonged fighting": "military conflict",
    "air attack": "violence",
    "locusts": "pest insect spread",
    "rival warlords": "militant group presence",
    "water distribution shortages": "water supply reduction",
    "militia groups": "militant group presence",
    "reduced imports": "economic factor decline",
    "prolonged dry spell": "drought conditions",
    "population crisis": "hazard exposure vulnerability condition",
    "floods": "flooding",
    "migration": "migrant influx",
    "environmental degradation": "degradation environment",
    "pests": "pest insect spread",
    "farmland loss or access": "shortcoming",
    "siege": "corridor blockade",
    "gastrointestinal distress": "human life threat",
    "drought": "drought conditions",
    "humanitarian disaster": "existing humanitarian crisis",
    "civil strife": "political instability",
    "economic collapse": "economic factor decline",
    "cholera outbreak": "disease outbreak",
    "land invasions": "violence",
    "withheld relief": "obstruction of humanitarian aid",
    "economic crisis": "economic situation affecting people",
    "cattle death": "resource depletion",
    "terrorism": "violence",
    "bombing campaign": "artillery bombing",
    "flee": "fled home population",
    "police torture": "rights violation",
    "natural disaster": "disaster event",
    "increased external debt": "economic factor decline",
    "aid worker deaths": "people killed",
    "lack of roads": "infrastructure degradation",
    "severe rains": "increased rainfall",
    "failed crops": "low crop yield",
    "insufficient rainfall": "drought conditions",
    "epidemics affecting agriculture": "disease outbreak",
    "land grab": "rights violation",
    "international embargo": "trade embargo",
    "blockade": "corridor blockade",
    "international terrorists": "militant group presence",
    "internal strife": "political instability",
    "makeshift camps": "lack of shelter",
    "land reform": "political instability",
    "forests destroyed": "deforested land",
    "economic impoverishment": "economic situation affecting people",
    "malnourished": "food scarcity",
    "restricted relief flights": "flight disruption",
    "restricted humanitarian access": "obstruction of humanitarian aid",
    "carbon emissions": "degradation environment",
    "call for donations": "financial contributions",
    "land seizures": "rights violation",
    "food insecurity": "food scarcity",
    "pirates": "violence",
    "foreign troops": "military conflict",
    "continued deterioration": "increased risk",
    "totalitarian rule": "political instability",
    "conflict": "military conflict",
    "acute hunger": "food scarcity",
    "human rights abuses": "rights violation",
    "military junta": "political instability",
    "lack of agricultural infrastructure": "infrastructure degradation",
    "toll on livestock": "resource depletion",
    "dependence on international aid": "food aid requirement",
    "mismanagement": "shortcoming",
    "displacement": "population affected by displacement",
    "the offensive": "military conflict",
    "tragedy": "traumatic situation",
    "gangs of bandits": "violence",
    "continued strife": "political instability",
    "rinderpest": "disease outbreak",
    "reduced national output": "economic factor decline",
    "clans": "militant group presence",
    "aid appeal": "financial contributions",
    "convoys": "obstruction of humanitarian aid",
    "food crisis": "food scarcity",
    "overthrow": "political instability",
    "cattle plague": "disease outbreak",
    "catastrophe": "disaster event",
    "foreign aid": "financial contributions",
    "international alarm": "increased risk",
    "collapse of government": "political instability",
    "dehydrated": "human life threat",
    "repression": "rights violation",
    "cycle of poverty": "economic situation affecting people",
    "rebel insurgency": "military conflict",
    "weather extremes": "climate event",
    "slashed export": "economic factor decline",
    "potato blight": "disease outbreak",
    "corrupt government": "political instability",
    "clan battle": "violence",
    "oppressive regimes": "rights violation",
    "unable to sow": "low crop yield",
    "price of food": "economic situation affecting people",
    "authoritarian rule": "political instability",
    "bad harvests": "low crop yield",
    "violent suppression": "rights violation",
    "brain drain": "economic factor decline",
    "price rise": "economic situation affecting people",
    "refugees": "refugee crisis",
    "years of warfare": "military conflict",
    "destructive pattern": "risk destruction",
    "transport bottleneck": "shortcoming",
    "harvest decline": "low crop yield",
    "rising food prices": "economic situation affecting people",
    "humanitarian situation": "existing humanitarian crisis",
    "self reliance": "shortcoming",
    "land degradation": "degradation environment",
    "hunger crises": "food scarcity",
    "secession": "political instability",
    "mass hunger": "food scarcity",
    "looting": "looting risk",
    "forced eviction from land": "rights violation",
    "apathy from starvation": "human life threat",
    "wreaked havoc": "disaster event",
    "regimes toppled": "political instability",
    "massive starvation": "human life threat",
    "military dictatorship": "political instability",
    "infrastructure damage": "infrastructure degradation",
    "water availability": "water supply reduction",
    "lack of alternatives": "shortcoming",
    "economic rise": "economic situation affecting people",
    "anti-western policies": "geopolitical risk",
    "ecological crisis": "degradation environment",
    "alarming level": "critical need",
    "mayhem": "violence",
    "life-threatening hunger": "human life threat",
    "man-made disaster": "disaster event",
    "slave trade": "rights violation",
    "climatic hazards": "climate event",
    "devastated the economy": "economic factor decline",
    "corruption": "political instability",
    "clan warfare": "military conflict",
    "brutal government": "rights violation",
    "coup": "political instability",
    "international intervention": "geopolitical risk",
    "lack of authority": "political instability",
    "lack of cultivation": "low crop yield",
    "poor soil quality": "degradation environment",
    "disrupted trade": "economic factor decline",
    "food assistance": "food aid requirement",
    "greenhouse gases": "degradation environment",
    "disruption to farming": "low crop yield",
    "dysfunction": "shortcoming",
    "power struggle": "political instability",
    "livestock deaths": "resource depletion",
    "asylum seekers": "refugee crisis",
    "climate change": "temperature increase climate change",
    "politically engineered": "political instability",
    "warlord": "militant group presence",
    "dictators": "political instability",
    "jihadist groups": "militant group presence",
    "infant mortality": "people killed",
    "burning houses": "fire destruction",
    "major offensive": "military conflict",
    "stolen food aid": "stolen food ration",
}

if __name__ == "__main__":
    argparser = argparse.ArgumentParser(
        description="Map event descriptions to ontology classes."
    )
    argparser.add_argument(
        "input_file", help="Path to the input JSONL file containing event descriptions."
    )
    argparser.add_argument(
        "output_file",
        help="Path to the output JSONL file for mapped event descriptions.",
    )
    args = argparser.parse_args()

    with open(args.input_file, "r", encoding="utf-8") as infile, open(
        args.output_file, "w", encoding="utf-8"
    ) as outfile:
        for line in infile:
            data = json.loads(line)
            if "events" in data:
                for event in data["events"]:
                    if event["event_type"] in MAPPING:
                        event["event_type"] = MAPPING[event["event_type"]]
                    else:
                        print(
                            f"Warning: '{event['event_type']}' not found in mapping. Keeping original."
                        )
            outfile.write(json.dumps(data) + "\n")
