### Model
model_name_or_path: Qwen/Qwen3.5-4B
template: qwen3_5_nothink
trust_remote_code: true

### Method
stage: sft
do_train: true
do_eval: false
finetuning_type: lora
lora_rank: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target: all

### Dataset
dataset: train
# eval_dataset: dev
cutoff_len: 16784
max_samples: 1000000
preprocessing_num_workers: 8

### Training
per_device_train_batch_size: 2
gradient_accumulation_steps: 16
per_device_eval_batch_size: 2
learning_rate: 2.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
max_grad_norm: 1.0
weight_decay: 0.01
optim: adamw_torch

### Evaluation & saving
# eval_strategy: steps
# eval_steps: 200
save_steps: 200
logging_steps: 5

### Generation (eval)
predict_with_generate: false
do_sample: false
temperature: 0
max_new_tokens: 4096

### Hardware
flash_attn: auto
bf16: true
packing: false
enable_thinking: false
ddp_timeout: 180000000
include_num_input_tokens_seen: true

### Tracking
report_to: wandb
run_name: qwen3_5-4b-risk-v4-train-vertex
plot_loss: true
